keys:
  - &um790 age1u8ah2hga53uh7y24efhuc5vszzctqxth2rtvd7dshedpl9l50d5slzs6zq
  - &b450m age1tuuaxwhcwygwfw4l9w77jn5xyeas2llj7sluyq8eueut56j4l9vqhxlacz

creation_rules:
  - path_regex: systems/nixos/services/hermes-agent/(secrets\.yaml|auth\.json)$
    key_groups:
      - age:
          - *um790
  - path_regex: systems/nixos/services/nextcloud/secrets/.*$
    key_groups:
      - age:
          - *b450m
