nextcloud-admin-pass: ENC[AES256_GCM,data:WKrJow==,iv:zu+jSOAl5nOq9SHv8kzPnfQZRl+8756uHwQe37LAaK8=,tag:u+GJsvKrDdUm/sC8TLAS4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGT2EvNThJRmdqT24zUlN0
        U1A4T3o5V2diSHBpRUtncU9EcWVMNkJMTndzCjJkUk5JUWtiOW5nS09obVRPRWtp
        cGh4YWdXUnBObzgzNmN3T1dvZGNlMkUKLS0tIFk1ZFY5R09mWHdCZDBCamlWZFBQ
        YzFGN1ZnRkJMdjVkeHJLNHp6QTQ1YjgKjiwIK/b8kO7T9rhtxLMq1S2OsLXIa4eP
        y2nl10Mea9S+a7BaOvW1+l2Fken8XS1hV5Vcts/djpzdtqM6czFw8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tuuaxwhcwygwfw4l9w77jn5xyeas2llj7sluyq8eueut56j4l9vqhxlacz
  lastmodified: '2026-05-16T16:43:12Z'
  mac: ENC[AES256_GCM,data:DxhrLIZbuUwAVjOWbP0TTFNXaLlcJoHQSYzo3yMS4brbDaxc0BFs+5DuqQwm+ONnB9NhT0/5ozBHoP16oDJCfveTE8q5GVHdll4dMyPeQhBh8y5cpwELnHidVRGF6geCW9kTI+ddSoSEo9HgP60ghCIznxF/2Ho3IlchHsBrNKI=,iv:wPEkI+FK2FrOQGkBjgR7iVrqqiAp6uwNjORJw1pTANA=,tag:yCsNGLJmbzVd9H5FuY9JWg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
