grafana-secret-key: ENC[AES256_GCM,data:eG0l6EYo39k/QIPVQ48CdKcRA+RFNq33lJfzYTr1m6HvBdAI9QT4H/6UCvwhU1cJifpFn59iPV+dK8PkaBA+yA==,iv:/JkCtUvOeMhtYMHKYtmxcMZ25ahi8UjMW3EfuiYciwg=,tag:bObBdftDLwRG+5GiBAXQig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNWc1Nk9pdU05ZDlZMnFy
        Z3hLU05SUjhiSGZxay9OWUdHK0xTOU9vdnhzCkt1YTNpSHZSaXFoVitoaXNsclJV
        WmlBK3pLSExEQTRVTWU5aDF6VmFwNFEKLS0tIDQ1eTI4NnJ6Vm4zYzZjcTJibDln
        dmpvaW9JQ1F6a3pCdjdQWmxOZ3ZXT00K7f9MWEXvqDGjOE6Kz1ftrxCT7ITzjEk0
        qpZUtCE5kP7huPtw5iQckyvQb7WZtUA4enM3VCIWB32sB1+AULqafg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tuuaxwhcwygwfw4l9w77jn5xyeas2llj7sluyq8eueut56j4l9vqhxlacz
  lastmodified: '2026-05-17T04:07:54Z'
  mac: ENC[AES256_GCM,data:7v4XIV0sY6gxLtMIca5P1m6/4iN5bvhVsC7nMvD3gjyZbMLoPmhUtzzvTNzXlEwBDldewq+Ti4LpX8/oP56PEBvL9VcrG/MqtTQ/3Dbv1kssSGF9CNOXvn8lKry2tq3CFNHupfhSNOeUKRwPAu0tp/lWPvr096a3+/nknJYLiOQ=,iv:f5DbjCqm9iV4obQD6x9vKxpCQJwjMfQcNItxJp37gQQ=,tag:6ubO6RQDk84lgl1f4d/UMw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
