approval_policy = "on-request"
model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
project_doc_fallback_filenames = ["CLAUDE.md"]
web_search_request = true

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[plugins."github@openai-curated"]
enabled = true

[projects."/home/yuta/ghq/github.com/yutakobayashidev/dotnix"]
trust_level = "trusted"

[projects."/home/yuta/ghq/github.com/yutakobayashidev/google-apps-script"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/dotnix"]
trust_level = "trusted"

[projects."/Users/yuta"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/contest"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/Litela-HQ/army-appointment-system-desktop"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/Litela-HQ/genki-up"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/homelab"]
trust_level = "trusted"

[projects."/Users/yuta/.Trash/keycloak-26.6.1"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/keycloak-26.6.1"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/keycloak/keycloak-26.6.1"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/keycloak/seccamp2026mini-testapp"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/keycloak"]
trust_level = "trusted"

[projects."/Users/yuta/ghq/github.com/yutakobayashidev/nur-packages"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.4"

[tui.model_availability_nux]
"gpt-5.5" = 4
