tailscale-authkey: ENC[AES256_GCM,data:A8m0WgFi/t2DXSgHGTufmrA917hj2l2xJJVidLtXM2wlpUjPwXypFjnQmmaKGs2Yusx4Ih5b2aXPelHt/MI=,iv:ZBamStOEjz9FeH7fqC/MTHFweNcWg5K2LYNSmeH56Vs=,tag:qqj8rEk6i52VoM6lzrRATQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcVA0ZTVCdUs3ekVqekg4
        TXB2RyszVUtLRnNYVDRYN0lzbmhhbHZ0bzFZCitkaFZ6UTMyRXJJUnQxYnJvWTRt
        UlFGVERHZHg1a3l4R2kwamhRNFlXekEKLS0tIEtrbUFqSXp3L2w5NTZhWlJ5L0Zk
        SWFlV2VWUG0wM0MxeFRnSW50Wk1BSTgKBjIeCLSEiriBPZ7Ld9eGOhX7fpgFSi1V
        DlQaY9AneZ2Zy/Kc1MNY7cJSo+dXZYeQAKnh+/wj9eFAHHysgGizYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u8ah2hga53uh7y24efhuc5vszzctqxth2rtvd7dshedpl9l50d5slzs6zq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU2JXTjBLQng1TmNhV0RP
        ejREelFNU3djREM3TWZFMkI3VWdvQ3pOSnlRCjhUYUxQcGRTUW1pNmFIRGtmcUxa
        Wm50QVhqYzBNazlpeWs3Unp0WnVnZEkKLS0tIGcvckxhNHBiRGdZT0tialllYk9N
        aXJYN3c1cWFkeGFpT2tYWEVWM0Y3ZlEKJr6psi0WdlZx/4DV+fbbb25sPTORxFJa
        O4nswHMg6CK2lNihG+MeUAX8OFXWGyActCLhyLKGhzUl0If3mgMHgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tuuaxwhcwygwfw4l9w77jn5xyeas2llj7sluyq8eueut56j4l9vqhxlacz
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWGw5OW94cXhFUzlOeEcr
        RGFOSEFuSnFZV1UvSGZrb0FpeWdhTnNIQzEwCngwbStzd3RSNkVMUGlkT1RGZkpi
        NUo5alpxYU5udk53WEhneW5JSkpVVGcKLS0tIGJhVE9FZHhxZGYwZmhoVmViOUxv
        TFNZNzE3S3BWYklkY0lnQ3BqcU1tMDgKXGDDnGpYIHo3/ZcejICQBTpWTYlsNQNN
        D7lFBHt1lXnr4mEmN/N7q0QZRXqNQyTqW/cGX1t7mTL/BB6e//mCiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a5cyt62c4ejr28d307x6prc2vrzvhugvelu7eq8vcs0gjmrjvuwq5vnd88
  lastmodified: '2026-05-17T05:37:19Z'
  mac: ENC[AES256_GCM,data:pd3/WZ+7h830erpaRAa4u4a7io/vfVWeU8bgQw6Al/Y+KhUe3E7ZMzH55HMdhex+PiluRVronSERjIN1wfnndHLbekZMuk6fxUU8aCBR6TD8XnBomSYyWfiZIUxvjPmluu//yikhC78xtlFtGnXEwRG30qRv0ppUoyKirSPOcqw=,iv:fiRl2Dz16c02+8bqd1htuBRgdxNofi43RervYlfyxv0=,tag:naUN1cLEu36uC90/ypOSQw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
